# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'githubBookmark' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for githubBookmark
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'
  pod 'FMDB'
  
  target 'githubBookmarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'githubBookmarkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
